plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

repositories {
    maven {
        name = 'TerraformersMC'
        url = 'https://maven.terraformersmc.com/'
    }
}

def modVersion = providers.gradleProperty('mod_version').get()
def archiveBaseName = providers.gradleProperty('archives_base_name').get()

version = modVersion
group = providers.gradleProperty('maven_group').get()

base {
    archivesName = archiveBaseName
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    compileOnly "com.terraformersmc:modmenu:${project.modmenu_version}"
}

processResources {
    inputs.property 'version', modVersion
    filesMatching('fabric.mod.json') {
        expand version: modVersion
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    from('LICENSE') {
        rename { "${it}_${archiveBaseName}" }
    }
}

test {
    useJUnitPlatform()
}
